<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><c:set var="pageTitle" value="${currentUser.customer?'My Tickets':'Ticket Queue'}"/><c:set var="pageKey" value="tickets"/><%@ include file="../includes/head.jsp" %>
<div class="page-toolbar">
    <form method="get" class="search-bar">
        <span class="search-field"><svg class="ui-icon sm"><use href="#icon-search"/></svg><input name="q" value="<c:out value='${search}'/>" placeholder="Ticket number or subject"></span>
        <select name="status"><option value="">All statuses</option><c:forEach items="${['OPEN','ASSIGNED','IN_PROGRESS','WAITING_FOR_CUSTOMER','ESCALATED','RESOLVED','CLOSED','CANCELLED','REOPENED']}" var="s"><option value="<c:out value='${s}'/>" ${selectedStatus eq s?'selected':''}>${s.replace('_',' ')}</option></c:forEach></select>
        <button class="btn btn-secondary icon-text"><svg class="ui-icon sm"><use href="#icon-filter"/></svg>Filter</button>
    </form>
    <c:if test="${currentUser.customer}"><a class="btn btn-primary icon-text" href="${pageContext.request.contextPath}/tickets?action=new"><svg class="ui-icon sm"><use href="#icon-plus"/></svg>New Ticket</a></c:if>
</div>
<section class="panel table-panel reveal"><div class="table-wrap"><table><thead><tr><th>Ticket</th><th>Customer / Category</th><th>Priority</th><th>Status</th><th>Assigned</th><th>Updated</th><th aria-label="Actions"></th></tr></thead><tbody><c:forEach items="${tickets}" var="ticket"><tr><td><a class="ticket-title" href="${pageContext.request.contextPath}/tickets?action=view&id=${ticket.id}"><b><c:out value="${ticket.subject}"/></b><span><c:out value="${ticket.number}"/></span></a></td><td><b><c:out value="${ticket.customerName}"/></b><small><c:out value="${ticket.categoryName}"/></small></td><td><span class="badge priority-${ticket.priority.toLowerCase()}">${ticket.priority}</span></td><td><span class="badge status-${ticket.status.toLowerCase().replace('_','-')}">${ticket.status.replace('_',' ')}</span></td><td><c:out value="${empty ticket.assigneeName?'Unassigned':ticket.assigneeName}"/></td><td><small>${ticket.updatedAt}</small></td><td><a class="icon-btn table-icon" href="${pageContext.request.contextPath}/tickets?action=view&id=${ticket.id}" title="View ticket" aria-label="View ticket"><svg class="ui-icon sm"><use href="#icon-eye"/></svg></a></td></tr></c:forEach><c:if test="${empty tickets}"><tr><td colspan="7"><div class="empty"><b>No matching tickets</b><span>Change the filters or create a new request.</span></div></td></tr></c:if></tbody></table></div></section><%@ include file="../includes/foot.jsp" %>