<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><c:set var="pageTitle" value="Dashboard"/><c:set var="pageKey" value="dashboard"/><%@ include file="includes/head.jsp" %>
<section class="welcome-panel reveal"><div><span class="eyebrow">${currentUser.roleLabel}</span><h2>Welcome, <c:out value="${currentUser.fullName}"/>.</h2><p>${currentUser.customer?'Track your requests and stay connected with the support team.':'Here is the latest view of customer-support activity and service performance.'}</p></div><c:choose><c:when test="${currentUser.customer}"><a class="btn btn-light icon-text" href="${pageContext.request.contextPath}/tickets?action=new"><svg class="ui-icon sm"><use href="#icon-plus"/></svg>New Ticket</a></c:when><c:otherwise><a class="btn btn-light icon-text" href="${pageContext.request.contextPath}/tickets"><svg class="ui-icon sm"><use href="#icon-ticket"/></svg>Tickets</a></c:otherwise></c:choose></section>
<section class="stat-grid">
    <article class="stat-card blue reveal"><span class="stat-label"><svg class="ui-icon sm"><use href="#icon-ticket"/></svg>Total Tickets</span><b>${stats.total}</b><small>Visible requests</small></article>
    <article class="stat-card cyan reveal delay-1"><span class="stat-label"><svg class="ui-icon sm"><use href="#icon-eye"/></svg>Open</span><b>${stats.open}</b><small>Awaiting action</small></article>
    <article class="stat-card amber reveal delay-2"><span class="stat-label"><svg class="ui-icon sm"><use href="#icon-message"/></svg>In Progress</span><b>${stats.inProgress}</b><small>Being handled</small></article>
    <article class="stat-card violet reveal delay-3"><span class="stat-label"><svg class="ui-icon sm"><use href="#icon-check"/></svg>Resolved</span><b>${stats.resolved}</b><small>Completed</small></article>
</section>
<section class="dashboard-grid"><article class="panel span-2"><div class="panel-head"><div><span class="section-kicker">Live workload</span><h3>Recent Tickets</h3></div><a class="text-link icon-text" href="${pageContext.request.contextPath}/tickets">View all <svg class="ui-icon sm"><use href="#icon-arrow"/></svg></a></div><div class="ticket-mini-list"><c:forEach items="${recentTickets}" var="ticket"><a href="${pageContext.request.contextPath}/tickets?action=view&id=${ticket.id}"><span class="priority-dot ${ticket.priority.toLowerCase()}"></span><div><b><c:out value="${ticket.subject}"/></b><small><c:out value="${ticket.number}"/> &middot; <c:out value="${ticket.categoryName}"/></small></div><span class="badge status-${ticket.status.toLowerCase().replace('_','-')}"><c:out value="${ticket.status.replace('_',' ')}"/></span></a></c:forEach><c:if test="${empty recentTickets}"><div class="empty"><b>No tickets yet</b><span>Your ticket activity will appear here.</span></div></c:if></div></article>
<article class="panel"><div class="panel-head"><div><span class="section-kicker">At a glance</span><h3>Service Pulse</h3></div></div><div class="pulse-ring" style="--score:${stats.satisfaction*20}"><div><b><c:out value="${stats.satisfaction}"/></b><span>Avg. rating</span></div></div><ul class="metric-list"><li><span>Escalated</span><b>${stats.escalated}</b></li><li><span>Closed</span><b>${stats.closed}</b></li><li><span>Unread alerts</span><b>${stats.unread}</b></li></ul></article></section>
<section class="quick-grid">
    <a href="${pageContext.request.contextPath}/faqs"><i><svg class="ui-icon"><use href="#icon-faq"/></svg></i><div><b>FAQs</b><span>Answers & knowledge content</span></div><strong><svg class="ui-icon sm"><use href="#icon-arrow"/></svg></strong></a>
    <a href="${pageContext.request.contextPath}/feedback"><i><svg class="ui-icon"><use href="#icon-feedback"/></svg></i><div><b>Feedback</b><span>Ratings & service comments</span></div><strong><svg class="ui-icon sm"><use href="#icon-arrow"/></svg></strong></a>
    <a href="${pageContext.request.contextPath}/profile"><i><svg class="ui-icon"><use href="#icon-profile"/></svg></i><div><b>Profile</b><span>Account & security</span></div><strong><svg class="ui-icon sm"><use href="#icon-arrow"/></svg></strong></a>
</section>
<%@ include file="includes/foot.jsp" %>
